aai:
  auth: 2A11B07DB6214A839394AA1EC5844695F5114FC407FF5422625FB00175A3DCB8A1FF745F22867EFA72D5369D599BBD88DA8BED4233CF5586
server:
  port: 8085

spring:
  datasource:
    hikari:
      jdbcUrl: jdbc:mariadb://mariadb:3306/catalogdb
      username: cataloguser
      password: catalog123
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: catdb-pool
      registerMbeans: false

  security:
    usercredentials:
    -
      username: asdc
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: Asdc-Client
    -
      username: mso_admin
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: ACTUATOR

request:
  datasource:
    hikari:
      jdbcUrl: jdbc:mariadb://mariadb:3306/requestdb
      username: requestuser
      password: request123
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: reqdb-pool
      registerMbeans: false

mso:
  msoKey: 07a7159d3bf51a0e53be7a8f89699be7
  logPath: ./logs/asdc
  catalog:
    db:
      spring:
        endpoint: http://catalog-db-adapter:8082
  db:
    auth: Basic YnBlbDpwYXNzd29yZDEk
  site-name: onapheat
  camundaURL: http://bpmn-infra:8081/
  adapters:
    requestDb:
      endpoint: http://request-db-adapter:8083
      auth: Basic YnBlbDpwYXNzd29yZDEk
  aai:
    endpoint: https://aai.api.simpledemo.onap.org:8443
  asdc-connections:
    asdc-controller1:
      user: mso
      consumerGroup: SO-OpenSource-Env11
      consumerId: SO-COpenSource-Env11
      environmentName: AUTO
      asdcAddress: c2.vm1.sdc.simpledemo.onap.org:8443
      password: 76966BDD3C7414A03F7037264FF2E6C8EEC6C28F2B67F2840A1ED857C0260FEE731D73F47F828E5527125D29FD25D3E0DE39EE44C058906BF1657DE77BF897EECA93BDC07FA64F
      pollingInterval: 60
      pollingTimeout: 60
      relevantArtifactTypes: HEAT,HEAT_ENV,HEAT_VOL
      useHttpsWithDmaap: false
      activateServerTLSAuth: false
      keyStorePassword:
      keyStorePath:
      watchDogTimeout: 100
      isFitlerInEmptyResources: true
      messageBusAddress: vm1.mr.simpledemo.onap.org,vm1.mr.simpledemo.onap.org
  asdc:
    config:
      activity:
        endpoint: http://sdc-wfd-be:8080
      key: 566B754875657232314F5548556D3665
      components:
        count: 0,
        componentNames:
  scheduling:
    enabled: false
