version: '2.1'
services:
  pmmapper:
    container_name: pmmapper
    image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.services.pm-mapper:latest
    ports:
      - "8081:8081"
    environment:
      CONFIG_BINDING_SERVICE_SERVICE_HOST: CBSIP
      CONFIG_BINDING_SERVICE_SERVICE_PORT: 10000
      HOSTNAME: pmmapper
    extra_hosts:
      - "dmaap-dr-node:1.1.1.1"
      - "message-router:4.4.4.4"