version: '3'
services:
################################################################################
  mariadb:
    image: mariadb:10.1.11
################################################################################
  catalog-db-adapter:
    image: onap/so/catalog-db-adapter:${TAG}
################################################################################
  request-db-adapter:
    image: onap/so/request-db-adapter:${TAG}
################################################################################
  sdnc-adapter:
    image: onap/so/sdnc-adapter:${TAG}
################################################################################
  sdc-controller:
    image: onap/so/sdc-controller:${TAG}
################################################################################
  bpmn-infra:
    image: onap/so/bpmn-infra:${TAG}
################################################################################
  api-handler-infra:
    image: onap/so/api-handler-infra:${TAG}
#############################################################################

