placementVersioningEnabled: False

# Placement API latest version numbers to be set in HTTP header
placementMajorVersion: "1"
placementMinorVersion: "0"
placementPatchVersion: "0"

# Placement API default version numbers to be set in HTTP header
placementDefaultMajorVersion: "1"
placementDefaultMinorVersion: "0"
placementDefaultPatchVersion: "0"

# Config for Conductor
conductorUrl: "http://127.0.0.1:5000/simulated/oof/has-api/flow1-success-simple/main.json"
conductorPingWaitTime: 2  # seconds to wait before calling the conductor retry URL
conductorMaxRetries: 5  # if we don't get something in 30 minutes, give up
# versions to be set in HTTP header
conductorMinorVersion: 0

# Policy Platform -- requires ClientAuth, Authorization, and Environment
policyPlatformUrl: http://127.0.0.1:5000/simulated/policy/pdpx/decision/v1 # Policy Dev platform URL
policyPlatformEnv: TEST  # Environment for policy platform

# Config for DMaaP
messageReaderHosts: https://DMAAP-HOST1:3905,https://DMAAP-HOST2:3905,https://DMAAP-HOST3:3905
messageReaderTopic: org.onap.oof.osdf.multicloud

# Config for SDC
sdcUrl: https://SDC-HOST:8443/sdc/v1/catalog
sdcONAPInstanceID: ONAP-OSDF

osdfPlacementUrl: "http://127.0.0.1:24699/osdf/api/v2/placement"

is_aaf_enabled: False
aaf_cache_expiry_hrs: 3
aaf_url: https://aaftest.simpledemo.onap.org:8095
aaf_user_roles:
    - /api/oof/v1/placement:org.onap.osdf.access|*|read ALL

# Secret Management Service from AAF
aaf_sms_url: http://aaf-sms.onap:10443
aaf_sms_timeout: 30
secret_domain: osdf
aaf_ca_certs: ssl_certs/aaf_root_ca.cer

# config db api
configDbUrl: http://127.0.0.1:5000/simulated/configdb
configDbGetCellListUrl: 'getCellList'
configDbGetNbrListUrl: 'getNbrList'

#key
appkey: