#
# ===========LICENSE_START====================================================
#  Copyright (C) 2020 AT&T Intellectual Property. All rights reserved.
# ============================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=====================================================
#
version: '2'
services:
   mariadb:
      image: mariadb:${POLICY_MARIADB_VER}
      container_name: mariadb
      hostname: mariadb
      command: ['--lower-case-table-names=1', '--wait_timeout=28800']
      env_file: ../config/db/db.conf
      volumes:
         - ../config/db:/docker-entrypoint-initdb.d:ro
      expose:
       - 3306
   policy.api.simpledemo.onap.org:
      image: policy/simulators
      container_name: policy.api.simpledemo.onap.org
      hostname: policy.api.simpledemo.onap.org
      volumes:
       - ../config/sim-all:/opt/app/policy/simulators/etc/parameters:ro
      expose:
       - 6666
       - 6668
       - 6669
       - 6670
       - 3905
   api:
      image: nexus3.onap.org:10001/onap/policy-api:${POLICY_API_VERSION}
      container_name: policy-api
      depends_on:
       - mariadb
      hostname: policy-api
      expose:
       - 6969
   pap:
      image: nexus3.onap.org:10001/onap/policy-pap:${POLICY_PAP_VERSION}
      container_name: policy-pap
      depends_on:
       - mariadb
      hostname: policy-pap
      expose:
       - 6969
      volumes:
       - ./custom/papDefaultConfig.json:/opt/app/policy/pap/etc/defaultConfig.json:ro
   policy-xacml-pdp:
      image: nexus3.onap.org:10001/onap/policy-xacml-pdp:${POLICY_XACML_PDP_VERSION}
      container_name: policy-xacml-pdp
      depends_on:
       - mariadb
       - policy.api.simpledemo.onap.org
      hostname: policy-xacml-pdp
      expose:
       - 6969
      volumes:
       - ./custom/xacmlDefaultConfig.json:/opt/app/policy/pdpx/etc/defaultConfig.json:ro
   drools:
      image: nexus3.onap.org:10001/onap/policy-pdpd-cl:${POLICY_DROOLS_APPS_VERSION}
      container_name: drools
      depends_on:
       - mariadb
       - policy.api.simpledemo.onap.org
      hostname: drools
      expose:
       - 6969
       - 9696
      volumes:
       - ../config/drools-apps/custom:/tmp/policy-install/config:ro
      env_file:
        - ../config/drools-apps/env/base.conf
        - ../config/drools-apps/env/feature-healthcheck.conf
        - ../config/drools-apps/env/feature-pooling-dmaap.conf
   start_dependencies:
      image: dadarek/wait-for-dependencies
      environment:
        TIMEOUT_LENGTH: 60
      container_name: policy-wait
      depends_on:
        - mariadb
        - policy.api.simpledemo.onap.org
      hostname: policy-wait
      command:
        mariadb:3306
        policy.api.simpledemo.onap.org:6666
        policy.api.simpledemo.onap.org:6668
        policy.api.simpledemo.onap.org:6669
        policy.api.simpledemo.onap.org:6670
        policy.api.simpledemo.onap.org:3905
   start_pap:
      image: dadarek/wait-for-dependencies
      environment:
        TIMEOUT_LENGTH: 120
      container_name: policy-wait-pap
      depends_on:
        - mariadb
        - policy.api.simpledemo.onap.org
        - pap
      hostname: policy-wait-pap
      command:
        mariadb:3306
        policy.api.simpledemo.onap.org:3905
        pap:6969
   start_all:
      image: dadarek/wait-for-dependencies
      environment:
        TIMEOUT_LENGTH: 120
      container_name: policy-wait-all
      depends_on:
        - mariadb
        - policy.api.simpledemo.onap.org
        - api
        - pap
        - policy-xacml-pdp
        - drools
      hostname: policy-wait-all
      command:
        mariadb:3306
        policy.api.simpledemo.onap.org:6666
        policy.api.simpledemo.onap.org:6668
        policy.api.simpledemo.onap.org:6669
        policy.api.simpledemo.onap.org:6670
        policy.api.simpledemo.onap.org:3905
        api:6969
        pap:6969
        drools:6969
